import { describe, expect, it } from "bun:test";
import { nextUltracodeReminder } from "@/engine/queue/runtime/markers.ts";
import type { SessionRecord } from "@/engine/session/record/index.ts";

const TS = "2026-07-03T00:00:00.000Z";

function enterRecord(reminderType: "full" | "sparse"): SessionRecord {
  return { type: "attachment", ts: TS, attachment: { type: "ultra_effort_enter", reminderType } };
}
function exitRecord(): SessionRecord {
  return { type: "attachment", ts: TS, attachment: { type: "ultra_effort_exit" } };
}
function userMessage(content = "hello"): SessionRecord {
  return { type: "user_message", ts: TS, content };
}
function metaUserMessage(content: string): SessionRecord {
  return { type: "user_message", ts: TS, content, isMeta: true };
}
function compactionBoundary(): SessionRecord {
  return { type: "compaction_mark", ts: TS, summary_ref: "summary" };
}
// The three user_message records persistLocalCommand writes per /command; all
// three carry isMeta.
function localCommandEcho(name: string, args: string): SessionRecord[] {
  return [
    metaUserMessage(
      `<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>`,
    ),
    metaUserMessage(
      `<command-name>/${name}</command-name>\n            <command-message>${name}</command-message>\n            <command-args>${args}</command-args>`,
    ),
    metaUserMessage(`<local-command-stdout>Set ${name} to ${args}</local-command-stdout>`),
  ];
}

describe("nextUltracodeReminder", () => {
  it("first activation with no prior marker → enter FULL", () => {
    const r = nextUltracodeReminder([userMessage()], true);
    expect(r.reminder).toEqual({ kind: "enter", reminderType: "full" });
    expect(r.enterRecord?.attachment).toEqual({ type: "ultra_effort_enter", reminderType: "full" });
  });

  it("re-activation after an exit → enter FULL again", () => {
    const r = nextUltracodeReminder([enterRecord("full"), exitRecord(), userMessage()], true);
    expect(r.reminder).toEqual({ kind: "enter", reminderType: "full" });
  });

  it("still on, last marker is enter, few human turns → no reminder", () => {
    const r = nextUltracodeReminder([enterRecord("full"), userMessage()], true);
    expect(r.reminder).toEqual({ kind: "none" });
    expect(r.enterRecord).toBeNull();
  });

  it("still on after 10 human turns since the enter → maintenance SPARSE", () => {
    const records: SessionRecord[] = [enterRecord("full")];
    for (let i = 0; i < 10; i++) records.push(userMessage(`turn ${i}`));
    const r = nextUltracodeReminder(records, true);
    expect(r.reminder).toEqual({ kind: "enter", reminderType: "sparse" });
    expect(r.enterRecord?.attachment).toEqual({
      type: "ultra_effort_enter",
      reminderType: "sparse",
    });
  });

  it("toggled off while last marker is enter → exit", () => {
    const r = nextUltracodeReminder([enterRecord("full"), userMessage()], false);
    expect(r.reminder).toEqual({ kind: "exit" });
    expect(r.exitRecord?.attachment).toEqual({ type: "ultra_effort_exit" });
  });

  it("off with no prior enter → no reminder", () => {
    const r = nextUltracodeReminder([userMessage()], false);
    expect(r.reminder).toEqual({ kind: "none" });
    expect(r.exitRecord).toBeNull();
  });

  it("meta user messages do not count toward the maintenance threshold", () => {
    const records: SessionRecord[] = [enterRecord("full")];
    for (let i = 0; i < 12; i++) records.push(metaUserMessage(`[synthetic echo ${i}]`));
    const r = nextUltracodeReminder(records, true);
    expect(r.reminder).toEqual({ kind: "none" });
  });

  it("a compaction boundary hides markers behind it → enter FULL re-fires", () => {
    const r = nextUltracodeReminder(
      [enterRecord("full"), userMessage(), compactionBoundary(), userMessage()],
      true,
    );
    expect(r.reminder).toEqual({ kind: "enter", reminderType: "full" });
  });

  it("a compaction boundary hides a prior enter → no spurious exit when off", () => {
    const r = nextUltracodeReminder(
      [enterRecord("full"), compactionBoundary(), userMessage()],
      false,
    );
    expect(r.reminder).toEqual({ kind: "none" });
  });

  it("markers after the compaction boundary still count", () => {
    const r = nextUltracodeReminder(
      [compactionBoundary(), enterRecord("full"), userMessage()],
      true,
    );
    expect(r.reminder).toEqual({ kind: "none" });
  });

  it("local-command echoes do not inflate the maintenance threshold", () => {
    const records: SessionRecord[] = [enterRecord("full")];
    // Four /command invocations = twelve echo records. Counting each (the prior
    // behavior) would clear the ten-turn threshold and fire a spurious SPARSE.
    for (let i = 0; i < 4; i++) records.push(...localCommandEcho("effort", "medium"));
    const r = nextUltracodeReminder(records, true);
    expect(r.reminder).toEqual({ kind: "none" });
  });

  it("real prompts still reach the threshold when interleaved with command echoes", () => {
    const records: SessionRecord[] = [enterRecord("full")];
    for (let i = 0; i < 10; i++) {
      records.push(userMessage(`turn ${i}`));
      records.push(...localCommandEcho("effort", "medium"));
    }
    const r = nextUltracodeReminder(records, true);
    expect(r.reminder).toEqual({ kind: "enter", reminderType: "sparse" });
  });
});
