const COMMAND_HINTS: Readonly<Record<string, string>> = {
  exit: "exit the TUI",
  clear: "clear conversation history",
  plan: "enter plan mode",
  fast: "toggle fast mode",
  parallel: "toggle parallel agent tasks",
  multiprovider: "set orchestration mode",
  copy: "copy an assistant response",
  export: "export this conversation",
  "toggle-memory": "toggle session memory",
  dream: "consolidate saved memories",
  "pr-review": "review a pull request",
  init: "initialize project instructions",
  loop: "repeat a prompt or command on an interval",
  btw: "ask without changing the thread",
  "pr-security-review": "review pending changes for security",
  "deep-security-review": "audit repository security",
  "grill-me": "stress-test a plan",
  ultraplan: "create a multi-agent plan",
  goal: "work until a condition is met",
  branch: "mark a point in the conversation",
  fork: "Spawn a background agent that inherits the full conversation",
  compact: "summarize and trim history",
  context: "show context usage",
  help: "show slash commands",
  resume: "continue a past session",
  rewind: "restore code or conversation state",
  config: "manage settings",
  orchestration: "manage orchestration mode and tier rosters",
  model: "switch the active model",
  theme: "switch the interface theme",
  effort: "set reasoning effort",
  permissions: "manage tool permissions",
  hooks: "manage event hooks",
  diff: "show code changes",
  skills: "list available skills",
  agents: "manage agent configurations",
  status: "show session status",
  usage: "show provider usage",
  stats: "show provider statistics",
  mcp: "manage MCP servers",
  plugins: "manage plugins",
  marketplace: "manage plugin marketplaces",
  reload: "reload skills, agents, and plugins",
  tasks: "manage background tasks",
  bashes: "manage background shells",
  workflows: "manage background workflows",
  remote: "manage remote sessions",
  login: "sign in to a provider",
  logout: "sign out of the current provider",
  design: "manage design sessions",
  "code-review": "review code changes",
};

export function commandHint(name: string, description: string): string {
  const mapped = COMMAND_HINTS[name.toLowerCase()];
  if (mapped) return mapped;
  const firstSentence = description.split(/[.!?](?:\s|$)/, 1)[0]?.trim();
  if (!firstSentence) return "run command";
  const words = firstSentence.split(/\s+/).slice(0, 7);
  return words.join(" ");
}
