import type { Message } from "@/kernel/std/types/message.ts";
import { appendRecord, nowIso, type Session, type UserMessageRecord } from "./index.ts";

export interface PersistLocalCommandArgs {
  session: Session;
  commandName: string; // e.g. "effort"
  args: string; // e.g. "medium"
  stdout: string; // e.g. "Set effort level to medium..."
  provider?: string;
  model?: string;
  permissionMode?: string;
}

export async function persistLocalCommand(opts: PersistLocalCommandArgs): Promise<void> {
  const { session, commandName, args, stdout, provider, model, permissionMode } = opts;
  const cleanName = commandName.startsWith("/") ? commandName.slice(1) : commandName;
  const ts = nowIso();

  const blockA = `<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>`;
  const blockB = `<command-name>/${cleanName}</command-name>\n            <command-message>${cleanName}</command-message>\n            <command-args>${args}</command-args>`;
  const blockC = `<local-command-stdout>${stdout}</local-command-stdout>`;

  const recordA: UserMessageRecord = {
    type: "user_message",
    ts,
    content: blockA,
    isMeta: true,
    ...(provider ? { provider } : {}),
    ...(model ? { model } : {}),
    ...(permissionMode ? { permissionMode } : {}),
  };
  const recordB: UserMessageRecord = {
    type: "user_message",
    ts,
    content: blockB,
    isMeta: true,
    ...(provider ? { provider } : {}),
    ...(model ? { model } : {}),
    ...(permissionMode ? { permissionMode } : {}),
  };
  const recordC: UserMessageRecord = {
    type: "user_message",
    ts,
    content: blockC,
    isMeta: true,
    ...(provider ? { provider } : {}),
    ...(model ? { model } : {}),
    ...(permissionMode ? { permissionMode } : {}),
  };

  await appendRecord(session, recordA);
  await appendRecord(session, recordB);
  await appendRecord(session, recordC);

  const msgA: Message = {
    role: "user",
    content: [{ type: "text", text: blockA }],
  };
  const msgB: Message = {
    role: "user",
    content: [{ type: "text", text: blockB }],
  };
  const msgC: Message = {
    role: "user",
    content: [{ type: "text", text: blockC }],
  };

  session.messages.push(msgA, msgB, msgC);
}
